name = "worker"
main = "./dist/index.mjs"
compatibility_date = "2023-01-05"

[build]
command = "npm install && npm test && npm run build"

[durable_objects]
bindings = [{name = "EDITOR", class_name = "Editor"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Editor"]
